# Numpy Tutorial

In [6]:
import numpy as nm
import time

In [10]:
myarray=nm.array([[1,2.4,4]],nm.int8) #creating the array with the numpy and determining the size of data type

In [11]:
myarray

array([[1, 2, 4]], dtype=int8)

In [12]:
myarray.shape

(1, 3)

In [13]:
myarray.dtype # willl give the data type and the size it is taking 

dtype('int8')

# Array Creation From other python structures

In [8]:
l=nm.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
l[0][0]

1

In [11]:
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
nm.array({1,2,3,3})

array({1, 2, 3}, dtype=object)

In [13]:
l.size

9

In [14]:
l=nm.zeros((3,2))

In [15]:
l

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
l.size

6

In [17]:
l.dtype

dtype('float64')

In [18]:
nm.arange(10) # create array of numbers from 0 to n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
lspace=nm.linspace(1,5,12) # this will give me  12 equally spaced elements from 1 to 5 

In [20]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [21]:
em=nm.empty((10)) # will create an array with the random elements of this size and you can initiallise further

In [22]:
em

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
emlike=nm.empty_like(lspace) # create the array of previous type

In [24]:
emlike

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
a=nm.identity((5)) # this will give me the identity matrix of n*n
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
a=nm.eye(3,4) # this will give me the identity matrix of n*m
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [27]:
a=nm.random.rand(10) # generate random numbers from 0-1
a

array([0.85861069, 0.21689613, 0.65588701, 0.34591908, 0.94019557,
       0.7980654 , 0.99652098, 0.84368938, 0.46049891, 0.58433716])

In [28]:
a=nm.random.rand(10)*10 # generate random numbers from 0-1 *10 ie 0-10
a

array([8.41973262, 4.30018523, 2.87935386, 0.80142099, 3.91589996,
       6.52431852, 1.42459254, 2.84239869, 9.53793424, 1.7658048 ])

In [29]:
a=nm.random.randint(1,10) # will generate any random number from 1-10
a=nm.random.randint(10,size=(4,4)) # for creating random int array ranging from 0-10 of size (4,4)
a

array([[7, 0, 5, 1],
       [1, 7, 8, 6],
       [1, 8, 4, 9],
       [6, 6, 4, 2]])

In [30]:
a=nm.arange(9,50)
a

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [31]:
a=nm.linspace(1,5,10)
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [32]:
# rounding  above upto2 decimals | syntax --> numpy.round_(arr, decimals = 0, out = None)
b=nm.round(a,decimals=2)
b

array([1.  , 1.44, 1.89, 2.33, 2.78, 3.22, 3.67, 4.11, 4.56, 5.  ])

In [33]:
l=[1,2,3,4,5]
arr=nm.array(l)
print(l)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [100]:
print(arr.data) # data -->  which represents the reference/adress of the array
print(*arr.data) # data -->  which represents the elements inside the above adress of the array
print(arr.shape) # shape --> which represents the size of my array
print(arr.dtype) #  dtype --> which represents the data type of array
print(arr.strides) # strides --> which represents the number of bytes to be skipped to get to the next element

1 2 3 4 5
(5,)
int32
(4,)


In [35]:
a=nm.arange(1,17).reshape(4,4)
a
print(a.data) # data -->  which represents the reference of 1st byte of the array
print(a.shape) # shape --> which represents the size of my array
print(a.dtype) #  dtype --> which represents the data type of array
print(a.strides) # (no.of bytes to be skipped to get to the next row,no.of bytes to be skipped to get to the next element in each row)

(4, 4)
int32
(16, 4)


In [102]:
# You can apply slicing in case of numpy arrays also
l=[1,2,3,4,5]
ar=nm.array(l)
print(l[2:5])
print(ar[2:4])

[3, 4, 5]
[3 4]


# Their is slight difference in case of python array and numpy array in 2D list

In [103]:
l=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
ar=nm.array(l)
print(l)
print(ar)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [105]:
# Suppose if we want to access 10
print(l[2][1])
print(ar[2][1])
print(ar[2,1]) # in case of numpy you can write in this way also but not in normal list

10
10
10


In [107]:
# Suppose if we want to access 5,6,7
print(l[1][:3])
print(ar[1,:3]) # we can do like this in case of numpy

[5, 6, 7]
[5 6 7]


In [110]:
# Suppose if we want to access 4,8,12,16
print(l[:][3]) # this is not giving me the desired output as it is fixing the row and iterating over the columns ie --> eg.
x=l[:]
y=x[3]
print(x)
print(y)

[13, 14, 15, 16]
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[13, 14, 15, 16]


In [118]:
# but we will get the correct ans in case of numpy
print(ar[:,3])  # ie ar[row number from starting to end,column number for that row]

[ 4  8 12 16]


In [120]:
# suppose we want to get 10,11,14,15 --> we can get it using numpy array ie
print(ar[2:,1:3])

[[10 11]
 [14 15]]


In [121]:
# PRACTICE
n=nm.arange(1,21).reshape(4,5)
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [127]:
# Print 11,12,13
print(n[2,:3])
# Print 9,14,19
print(n[1:,3])
# Print 11-15 and 16-20
print(n[2:,:])
# Print 7,8,12,13
print(n[1:3,1:3])

[11 12 13]
[ 9 14 19]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8]
 [12 13]]


# Mathematical Operrations

In [129]:
li=[1,2,3,4,5]
a=nm.random.randint(1,20,5)
b=nm.random.randint(1,20,5)
print(a)
print(b)

[12  9 17 16 13]
[18 12 10  1  3]


In [130]:
li=[i+1 for i in li] # you have to iterate through each element to add 1 but for numpy array you dont have to iterate 
print(li)

[2, 3, 4, 5, 6]


In [131]:
a=a+1
print(a)

[13 10 18 17 14]


In [133]:
# You can also perform alot of operations using numpy arrays like
c=a+b
print(c)
c=a-b
print(c)
c=a/b
print(c)
c=a//b
print(c)
c=a**b
print(c)


[31 22 28 18 17]
[-5 -2  8 16 11]
[ 0.72222222  0.83333333  1.8        17.          4.66666667]
[ 0  0  1 17  4]
[ -76943639 -727379968 1349403648         17       2744]


In [138]:
print(a)               # You can perform multiple operations using numpy array
print(a.max())
print(a.argmax())
print(a.min())
print(a.argmin())
print(a.mean())
print(a.sum())

[13 10 18 17 14]
18
2
10
1
14.4
72


In [139]:
# You can also perform the relational operations and logical operations
print(a)
print(b)

[13 10 18 17 14]
[18 12 10  1  3]


In [140]:
a>b

array([False, False,  True,  True,  True])

In [141]:
a<b

array([ True,  True, False, False, False])

In [142]:
a==b

array([False, False, False, False, False])

In [144]:
# You can also perform the logical operations using logical_or <--> logical_and <--> logical_not
print(nm.logical_or(a,b))
print(nm.logical_and(a,b))
print(nm.logical_not(a))

[ True  True  True  True  True]
[False False False False False]
[False False False False False]



# Boolean Indexing

In [147]:
a=nm.array(['a','b','c','d','e','f','g','h'])
b=nm.random.randint(1,20,8)
print(a)

print(b)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h']
[15  6 16 18 12 11 16 15]


In [150]:
bool_arr=b>10
print(bool_arr) # or print(b>10)
# suppose if I want to extract all the elements of array which are greater than 10
new_ar=b[bool_arr]
print(new_ar)

[ True False  True  True  True  True  True  True]
[15 16 18 12 11 16 15]


In [153]:
new_arr=b[(b>10) & (b<15)]
print(new_arr)

[12 11]


In [158]:
c=b
c[:3]=19 # you can also update multiple elements in one go
print(c)
c[c>14]=100
print(c)
print(c[c==100])
# if you want to print indexes where c==100
indx=nm.where(c==100) # indeces where c==100
print(indx)
# suppose if you want to print a[i] only when b[i]==100
d=a[indx]
print(d)

[ 19  19  19 100  12  11 100 100]
[100 100 100 100  12  11 100 100]
[100 100 100 100 100 100]
(array([0, 1, 2, 3, 6, 7], dtype=int64),)
['a' 'b' 'c' 'd' 'g' 'h']


In [168]:
# replace odd integers with -1
x=nm.arange(1,11)
print(x)
x[nm.where(x%2!=0)]=-1
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [179]:
age=nm.random.randint(15,20,20)
height=nm.random.randint(120,200,20)
print("age",age)
print("height",height)
print(nm.where(height>155))
print(age[nm.where(height>155)])

age [16 16 18 16 18 15 15 19 15 17 17 16 18 18 16 19 15 19 16 15]
height [121 187 182 127 130 134 131 186 142 154 147 198 193 162 140 141 128 194
 145 171]
(array([ 1,  2,  7, 11, 12, 13, 17, 19], dtype=int64),)
[16 18 19 16 18 18 19 15]


# Boolean Expression For 2D array

In [201]:
a=nm.random.randint(1,30,(5,6))
print(a)

[[18 23  7 17 12 28]
 [ 7 25 14 29  1 18]
 [ 3 14 21 17 24  2]
 [ 6 24  9  1 19 29]
 [ 6 27 28 10 16 13]]


In [202]:
a>20

array([[False,  True, False, False, False,  True],
       [False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False],
       [False,  True, False, False, False,  True],
       [False,  True,  True, False, False, False]])

In [203]:
b=a[a>20]
b

array([23, 28, 25, 29, 21, 24, 24, 29, 27, 28])

In [204]:
# suppose if you want to update the value if b>20 replace it with 100
d=a
d[d>20]=100
d


array([[ 18, 100,   7,  17,  12, 100],
       [  7, 100,  14, 100,   1,  18],
       [  3,  14, 100,  17, 100,   2],
       [  6, 100,   9,   1,  19, 100],
       [  6, 100, 100,  10,  16,  13]])

In [205]:
bool_arr=d[:,3]==100 # if you want to perform operation for the particular row or column or both not all you canuse slicing
bool_arr

array([False,  True, False, False, False])

In [206]:
d[bool_arr,3]=99
d

array([[ 18, 100,   7,  17,  12, 100],
       [  7, 100,  14,  99,   1,  18],
       [  3,  14, 100,  17, 100,   2],
       [  6, 100,   9,   1,  19, 100],
       [  6, 100, 100,  10,  16,  13]])

In [220]:
# IMP... Sort the given 2D array in the acsending order of the 2nd column(index=1) elements
x=nm.arange(21,1,-1).reshape(4,5)
print(x)

[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]


In [221]:
idx=x[:,1].argsort() # will return the order of indexes of the elements so as to be the sorted order
print(idx)

[3 2 1 0]


In [222]:
x=x[idx]
x

array([[ 6,  5,  4,  3,  2],
       [11, 10,  9,  8,  7],
       [16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17]])

# Broadcasting

In [224]:
# For performing operation on 2 arrays n*m either the order shoud be same ie (m*n) or any one having (m*1) or (1*m)
# in case of (1*m) or (m*1) broadcasting is performed ie the elements in the single row or column are replicated such that size
# could be matched

In [228]:
f=nm.array(['a','b','c','d','e','f','g','h'])
f.sort()
print(f)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h']


In [230]:
s=nm.array(['1','3','4'],dtype=int)
s

array([1, 3, 4])

In [237]:
a=nm.array([])
a=nm.append(a,3)
a=nm.append(a,3)
a



array([3., 3.])

In [37]:
a.shape # will give me the (no. of rows,no. of columns) of a matrix

(4, 4)

In [38]:
a=nm.arange(99)

In [39]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
a=a.reshape(3,33) # this will convert the list into 3 rows having 33 columns each ->condition: n*m=value given above ie 3*33=99

In [41]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [42]:
a=a.ravel() # convert back into 1d array

In [43]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
a.shape

(99,)

# Axis 

In [45]:
x=[[1,2,3],[4,5,6],[7,8,9]] # For 1d array axis=0 but for 2 d array top to bottom ie column wise --> axis 0 and
                            # left to right ie row wise --> axis 1

In [46]:
a=nm.array(x)

In [47]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
print(a.sum(axis=0),a.sum(axis=1))

[12 15 18] [ 6 15 24]


In [49]:
a=a.T # this will transpose my array

In [50]:
array 

NameError: name 'array' is not defined

In [ ]:
a

In [ ]:
for i in a.flat: # .flat will give me the iterator and you can print all the elements of the array wheather 2D or 1d
    print(i)

In [51]:
for i in a:
    print(i)

[1 4 7]
[2 5 8]
[3 6 9]


In [52]:
a.ndim # will print dimension of array

2

In [53]:
a.nbytes # this will give the total bytes consumed by the array

36

# Attributes


In [54]:
one =nm.array([1,5,522,2,5])


In [55]:
one.argmax() # will return the index of maximum element

2

In [56]:
one.argmin() # will return the index of minimum element

0

In [57]:
one.argsort() # will return the indices of the elements in the ascending order 

array([0, 3, 1, 4, 2], dtype=int64)

In [58]:
one.sort()

In [59]:
one

array([  1,   2,   5,   5, 522])

In [60]:
one.max()

522

In [61]:
one.min()

1

In [62]:
ar=nm.array([[1,2,3],[4,5,6],[7,1,0]],nm.int8)

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]], dtype=int8)

In [64]:
ar.argmin() # it will first convert it into 1d array and then give the index of min element

8

In [65]:
ar.argmax() # it will first convert it into 1d array and then give the index of max element

6

In [66]:
ar.argsort() # this give the order of ideces which tells the elements of that index should be like this for the ascending order

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [67]:
ar.sort(axis=0) # elements get sorted along the columns

In [68]:
ar

array([[1, 1, 0],
       [4, 2, 3],
       [7, 5, 6]], dtype=int8)

In [69]:
ar.ravel()

array([1, 1, 0, 4, 2, 3, 7, 5, 6], dtype=int8)

In [70]:
ar.reshape((9,1)) # ypu can reshape the matrix

array([[1],
       [1],
       [0],
       [4],
       [2],
       [3],
       [7],
       [5],
       [6]], dtype=int8)

# You can perform matrix operations in Numpy for example addition subtraction and multiplication

In [71]:
ar1=nm.array([[1,2,3],[4,5,6],[7,1,0]])

In [72]:
ar2=nm.array([[1,0,0],[3,0,0],[2,0,0]])

In [73]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [74]:
ar2

array([[1, 0, 0],
       [3, 0, 0],
       [2, 0, 0]])

In [75]:
ar1*ar2 multiply element wise elemnt

SyntaxError: invalid syntax (Temp/ipykernel_888/2478096466.py, line 1)

In [ ]:
ar1+ar2

In [76]:
nm.sqrt(ar1) # take the square root of each element in the matrix

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [77]:
ar1.min()

0

In [78]:
ar1.max()

7

In [79]:
ar1.sum()

29

In [80]:
nm.where(ar1>5) # this will give me the tuple of the array index positions where the condition holds true

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [81]:
nm.count_nonzero(ar1)

8

In [82]:
ar1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [83]:
nm.nonzero(ar1) # this will give me the pair of indeces of non zero element of each row

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

## numpy takes less size as compare to python

In [84]:
import sys

In [85]:
py_ar=[1,2,3,4]

In [86]:
nm_ar=nm.array([1,2,3,4])


In [87]:
sys.getsizeof(1)*len(py_ar)

112

In [88]:
nm_ar.itemsize*nm_ar.size

16

# Numpy Coding Ninjas

In [89]:
import time
size=100000
def addition_using_list():
    t1=time.time()
    a=range(size)
    b=range(size)
    c=[a[i]+b[i] for i in range(size)]
    t2=time.time()
    return (t2-t1)
def addition_using_numpy():
    t1=time.time()
    a=nm.arange(size)
    b=nm.arange(size)
    c=a+b
    t2=time.time()
    return (t2-t1)


In [90]:
t_list=addition_using_list()
t_numpy=addition_using_numpy()
print("list -->",t_list*1000)
print("numpy -->",t_numpy*1000)  # this shows numpy library takes less time and memory as compare to the python lists

list --> 65.0022029876709
numpy --> 1.001119613647461


In [91]:
b=[1,2,3,4]
b=nm.array(b,dtype=float)
b

array([1., 2., 3., 4.])

In [92]:
b.dtype

dtype('float64')

In [93]:
b=nm.ones(3,dtype=int) # for 1 D
print(b) 
b=nm.ones(3,dtype=float)
print(b)

b=nm.ones((3,2),dtype=int) # for 2 D
print(b) 
b=nm.ones((2,4),dtype=float)
print(b)


[1 1 1]
[1. 1. 1.]
[[1 1]
 [1 1]
 [1 1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [94]:
b=nm.zeros(3,dtype=int) # for 1 D
print(b) 
b=nm.zeros(3,dtype=float)
print(b)

b=nm.zeros((3,2),dtype=int) # for 2 D
print(b) 
b=nm.zeros((2,4),dtype=float)
print(b)

[0 0 0]
[0. 0. 0.]
[[0 0]
 [0 0]
 [0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [95]:
b=nm.full(5,3) # nm.full(size of array,element you want to add) --> 1D
b

array([3, 3, 3, 3, 3])

In [96]:
b=nm.full((3,3),4) # nm.full(size of array,element you want to add) --> 2D
b

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [97]:
a=nm.arange(10)
a=nm.where(a!=4,0,1).reshape(10)  
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [98]:
V=nm.arange(9)
V=nm.where(V!=4,0,1).reshape((3,3))  # nm.where( condition with variable_name,if True, if False ) similar to 
V                                    # ternery operator --> condition?():()

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

# NUMPY .WHERE FOR CONDITION

In [99]:
a = nm.arange(9).reshape((3, 3))
print(a)
# [[0 1 2]
#  [3 4 5]
#  [6 7 8]]

print(nm.where(a < 4, -1, 100))
# [[ -1  -1  -1]
#  [ -1 100 100]
#  [100 100 100]]

print(nm.where(a < 4, True, False))
# [[ True  True  True]
#  [ True False False]
#  [False False False]]

print(a < 4)
# [[ True  True  True]
#  [ True False False]
#  [False False False]]

print(nm.where((a > 2) & (a < 6), -1, 100))
# [[100 100 100]
#  [ -1  -1  -1]
#  [100 100 100]]

print(nm.where((a > 2) & (a < 6) | (a == 7), -1, 100))
# [[100 100 100]
#  [ -1  -1  -1]
#  [100  -1 100]]

print((a > 2) & (a < 6))
# [[False False False]
#  [ True  True  True]
#  [False False False]]

print((a > 2) & (a < 6) | (a == 7))
# [[False False False]
#  [ True  True  True]
#  [False  True False]]

print(nm.where(a < 4, -1, a))
# [[-1 -1 -1]
#  [-1  4  5]
#  [ 6  7  8]]

print(nm.where(a < 4, a, 100))
# [[  0   1   2]
#  [  3 100 100]
#  [100 100 100]]

a_org = nm.arange(9).reshape((3, 3))
print(a_org)
# [[0 1 2]
#  [3 4 5]
#  [6 7 8]]

a_new = nm.where(a_org < 4, -1, a_org)
print(a_new)
# [[-1 -1 -1]
#  [-1  4  5]
#  [ 6  7  8]]

print(a_org)
# [[0 1 2]
#  [3 4 5]
#  [6 7 8]]

a_org[a_org < 4] = -1
print(a_org)
# [[-1 -1 -1]
#  [-1  4  5]
#  [ 6  7  8]]

print(nm.where(a < 4, a * 10, a))
# [[ 0 10 20]
#  [30  4  5]
#  [ 6  7  8]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ -1  -1  -1]
 [ -1 100 100]
 [100 100 100]]
[[ True  True  True]
 [ True False False]
 [False False False]]
[[ True  True  True]
 [ True False False]
 [False False False]]
[[100 100 100]
 [ -1  -1  -1]
 [100 100 100]]
[[100 100 100]
 [ -1  -1  -1]
 [100  -1 100]]
[[False False False]
 [ True  True  True]
 [False False False]]
[[False False False]
 [ True  True  True]
 [False  True False]]
[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]
[[  0   1   2]
 [  3 100 100]
 [100 100 100]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]
[[ 0 10 20]
 [30  4  5]
 [ 6  7  8]]


In [ ]:
t1=time.time() # not a better solution to append a numpy array as it takes more time as compare to list
file_obj=open('year2017.csv','r')
file_data=csv.DictReader(file_obj,skipinitialspace=True)
killed=nm.array([])
wounded=nm.array([])
country=nm.array([]) # empty list
for row in file_data:
    killed=nm.append(killed,row['Killed'])
    wounded=nm.append(wounded,row['Wounded'])
    country=nm.append(country,row['Country'])
killed[killed=='']='0'
killed=nm.array(killed,dtype=float)
wounded[wounded=='']='0'
wounded=nm.array(wounded,dtype=float)
k_w=killed+wounded
print(sum(k_w))
print(sum(k_w[country=='India']))
t2=time.time()
print(f"time taken to be executed is {(t2-t1)}s")

In [ ]:
import numpy as nm
import csv
import time
t1=time.time() 
file_obj=open('year2017.csv','r')
file_data=csv.DictReader(file_obj,skipinitialspace=True)
killed=[]
wounded=[]
country=[]
for row in file_data:
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    country.append(row['Country'])
killed=nm.array(killed)
wounded=nm.array(wounded)

killed[killed=='']='0'
wounded[wounded=='']='0'

killed=nm.array(killed,dtype=float)
wounded=nm.array(wounded,dtype=float)
country=nm.array(country)
bool=country=='India'
k_w=killed+wounded # this will give the array of killed + wounded
print(sum(k_w[country=='India']))
t2=time.time()
print(f"time taken to be executed is {(t2-t1)}s")